### PR TITLE
Fix #5 - no longer using non-existent std.stream

### LINKED ISSUE #5: strict.d(19,8): module std.stream is deprecated
../../.dub/packages/dlogg-0.4.0/source/dlogg/strict.d(19,8): Deprecation: module std.stream is deprecated - It will be removed from Phobos in October 2016. If you still need it, go to https://github.com/DigitalMars/undeaD

### PR DESCRIPTION
**Pull request by atilaneves**

### CODE REVIEW

**Comment by NCrashed** [comment]
Thank you!

**Comment by atilaneves** [comment]
No worries. Could you please tag a new version so that daemonize can use that instead? Thanks.

**Comment by NCrashed** [comment]
https://github.com/NCrashed/dlogg/releases/tag/v0.4.1

**Comment by atilaneves** [comment]
Thanks!

**Pull request merged**
